"""Revertir cambio

Revision ID: 71a7d1119ed3
Revises: d8b5a96c6ccc
Create Date: 2026-02-25 20:23:01.603745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71a7d1119ed3'
down_revision = 'd8b5a96c6ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', sa.String(length=50), nullable=True))
        batch_op.drop_column('apellidos')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('apellidos', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('apaterno')

    # ### end Alembic commands ###
